---
name: Backend Lint

"on":
  workflow_dispatch:
  workflow_call:

jobs:
  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry --quiet
      - name: Install dependencies
        working-directory: backend
        run: poetry install --only=main,dev --quiet
      - name: Run pre-commit
        working-directory: backend
        run: poetry run pre-commit run --all-files
