---
name:  Backend Build & Push

# Migrated from GitLab CI - supports manual dispatch
"on":
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag the Docker image with'
        required: false
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version to tag the Docker image with'
        required: false
        type: string

permissions:
  contents: read
  packages: write

jobs:
  # Build and push backend container - migrated from build-container-backend
  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
          fi
          echo "SHORT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
          # Set image name for backend
          LLM_EVAL_BACKEND_IMAGE="ghcr.io/${{ github.repository }}"
          LLM_EVAL_BACKEND_IMAGE="${LLM_EVAL_BACKEND_IMAGE}/llm-eval-backend"
          echo "LLM_EVAL_BACKEND_IMAGE=${LLM_EVAL_BACKEND_IMAGE}" >> \
            $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend container
        uses: docker/build-push-action@v6
        with:
          context: backend/
          file: backend/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.LLM_EVAL_BACKEND_IMAGE }}:${{ env.SHORT_SHA }}
            ${{ github.ref_type == 'tag' &&
                format('{0}:{1}', env.LLM_EVAL_BACKEND_IMAGE,
                       github.ref_name) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Tag and push semantic version if version was provided
      - name: Tag and push semantic version
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && inputs.version != ''
        run: |
          # Use the version provided by the bulk release workflow
          NEW_VERSION="${{ inputs.version }}"
          echo "Using version from bulk release: $NEW_VERSION"
          # Create backend-prefixed version tag
          BACKEND_VERSION="backend-v$NEW_VERSION"
          echo "Using release tag: $BACKEND_VERSION"
          
          # Tag the existing image with the backend-prefixed semantic version
          docker pull ${{ env.LLM_EVAL_BACKEND_IMAGE }}:${{ env.SHORT_SHA }}
          docker tag ${{ env.LLM_EVAL_BACKEND_IMAGE }}:${{ env.SHORT_SHA }} ${{ env.LLM_EVAL_BACKEND_IMAGE }}:$BACKEND_VERSION
          docker push ${{ env.LLM_EVAL_BACKEND_IMAGE }}:$BACKEND_VERSION
          echo "Tagged and pushed image with backend version: $BACKEND_VERSION"
