---
name: Backend Pipeline

"on":
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

permissions:
  contents: read
  security-events: write
  actions: read
  packages: write

jobs:
  # Parallel execution of lint, security-scan, and test workflows
  lint:
    name: Run Lint
    uses: ./.github/workflows/backend-lint.yaml

  security-scan:
    name: Run Security Scan
    uses: ./.github/workflows/security-scan.yaml

  test:
    name: Run Tests
    uses: ./.github/workflows/backend-test.yaml

  # Sequential build stage - runs only after parallel jobs succeed
  build-and-push:
    name: Build and Push
    needs: [lint, security-scan, test]
    uses: ./.github/workflows/backend-build-and-push.yaml
