---
name: Build & Push

# Migrated from GitLab CI - supports manual dispatch
"on":
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  # Build and push frontend container - migrated from build-container-ui
  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
          fi
          echo "SHORT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
          # Set image name for frontend
          RAG_EVAL_UI_IMAGE="ghcr.io/${{ github.repository }}/rag-eval-ui"
          echo "RAG_EVAL_UI_IMAGE=${RAG_EVAL_UI_IMAGE}" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend container
        uses: docker/build-push-action@v6
        with:
          context: frontend/
          file: frontend/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
          push: true
          tags: |
            ${{ env.RAG_EVAL_UI_IMAGE }}:${{ env.SHORT_SHA }}
            ${{ github.ref_type == 'tag' &&
                format('{0}:{1}', env.RAG_EVAL_UI_IMAGE,
                       github.ref_name) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Build and push backend container - migrated from build-container-backend
  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
          fi
          echo "SHORT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
          # Set image name for backend
          LLM_EVAL_BACKEND_IMAGE="ghcr.io/${{ github.repository }}"
          LLM_EVAL_BACKEND_IMAGE="${LLM_EVAL_BACKEND_IMAGE}/llm-eval-backend"
          echo "LLM_EVAL_BACKEND_IMAGE=${LLM_EVAL_BACKEND_IMAGE}" >> \
            $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend container
        uses: docker/build-push-action@v6
        with:
          context: backend/
          file: backend/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
          push: true
          tags: |
            ${{ env.LLM_EVAL_BACKEND_IMAGE }}:${{ env.SHORT_SHA }}
            ${{ github.ref_type == 'tag' &&
                format('{0}:{1}', env.LLM_EVAL_BACKEND_IMAGE,
                       github.ref_name) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
