---
name: Bulk Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release:
    name: Bulk Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    outputs:
      frontend-released: ${{ steps.release.outputs.frontend-released }}
      backend-released: ${{ steps.release.outputs.backend-released }}
      frontend-version: ${{ steps.release.outputs.frontend-version }}
      backend-version: ${{ steps.release.outputs.backend-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run zx-bulk-release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run release
          
          # Check if releases were created and extract versions from tags
          LATEST_TAGS=$(git tag -l | tail -10)
          echo "Latest tags: $LATEST_TAGS"
          
          # Check for frontend release
          FRONTEND_TAG=$(git tag -l | grep "rag-eval-ui" | tail -1)
          if [ -n "$FRONTEND_TAG" ]; then
            echo "frontend-released=true" >> $GITHUB_OUTPUT
            FRONTEND_VERSION=$(echo "$FRONTEND_TAG" | grep -o 'v\?[0-9]\+\.[0-9]\+\.[0-9]\+[^-]*' | head -1)
            echo "frontend-version=$FRONTEND_VERSION" >> $GITHUB_OUTPUT
            echo "frontend-tag=$FRONTEND_TAG" >> $GITHUB_OUTPUT
          else
            echo "frontend-released=false" >> $GITHUB_OUTPUT
          fi
          
          # Check for backend release
          BACKEND_TAG=$(git tag -l | grep "llm-eval-backend" | tail -1)
          if [ -n "$BACKEND_TAG" ]; then
            echo "backend-released=true" >> $GITHUB_OUTPUT
            BACKEND_VERSION=$(echo "$BACKEND_TAG" | grep -o 'v\?[0-9]\+\.[0-9]\+\.[0-9]\+[^-]*' | head -1)
            echo "backend-version=$BACKEND_VERSION" >> $GITHUB_OUTPUT
            echo "backend-tag=$BACKEND_TAG" >> $GITHUB_OUTPUT
          else
            echo "backend-released=false" >> $GITHUB_OUTPUT
          fi

  frontend-build-and-push:
    name: Frontend Build and Push
    needs: [release]
    if: needs.release.outputs.frontend-released == 'true'
    uses: ./.github/workflows/frontend-build-and-push.yaml
    secrets: inherit
    with:
      version: ${{ needs.release.outputs.frontend-version }}

  backend-build-and-push:
    name: Backend Build and Push  
    needs: [release]
    if: needs.release.outputs.backend-released == 'true'
    uses: ./.github/workflows/backend-build-and-push.yaml
    secrets: inherit
    with:
      version: ${{ needs.release.outputs.backend-version }}