---
name: Frontend Build & Push

# Migrated from GitLab CI - supports manual dispatch
"on":
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  # Build and push frontend container - migrated from build-container-ui
  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Set initial version (pre-build)
        id: pre-version
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
          # Set image name for frontend
          FRONTEND_IMAGE="ghcr.io/${{ github.repository }}/frontend"
          echo "FRONTEND_IMAGE=${FRONTEND_IMAGE}" >> $GITHUB_ENV
          
          # Set initial version for build
          echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
         

      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend container
        uses: docker/build-push-action@v6
        with:
          context: frontend/
          file: frontend/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.FRONTEND_IMAGE }}:${{ env.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Only run semantic release after successful build on main branch
      - name: Run semantic-release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd frontend
          npm run semantic-release

      # If semantic release created a new version, tag and push the Docker image with semantic version
      - name: Tag and push semantic version
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.semantic.outcome == 'success'
        run: |
          cd frontend
          # Get the version from package.json after semantic-release
          NEW_VERSION=$(node -p "require('./package.json').version")
          
          if [ -n "$NEW_VERSION" ] && [ "$NEW_VERSION" != "null" ]; then
            echo "Semantic release created version: $NEW_VERSION"
            # Create frontend-prefixed version tag
            FRONTEND_VERSION="frontend-v$NEW_VERSION"
            echo "Creating release tag: $FRONTEND_VERSION"
            
            # Create and push git tag for frontend release
            git tag "$FRONTEND_VERSION"
            git push origin "$FRONTEND_VERSION"
            
            # Tag the existing image with the frontend-prefixed semantic version
            docker pull ${{ env.FRONTEND_IMAGE }}:${{ env.SHORT_SHA }}
            docker tag ${{ env.FRONTEND_IMAGE }}:${{ env.SHORT_SHA }} ${{ env.FRONTEND_IMAGE }}:$FRONTEND_VERSION
            docker push ${{ env.FRONTEND_IMAGE }}:$FRONTEND_VERSION
            echo "Tagged and pushed image with frontend version: $FRONTEND_VERSION"
          else
            echo "No new version was created by semantic-release"
          fi
