---
name: Frontend Build & Push

# Migrated from GitLab CI - supports manual dispatch
"on":
  workflow_dispatch:
  workflow_call:
    inputs:
      semantic-version:
        description: 'Semantic version from semantic-release'
        required: false
        type: string
      use-semantic-version:
        description: 'Whether to use semantic version for tagging'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:
  # Build and push frontend container - migrated from build-container-ui
  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          if [ "${{ inputs.use-semantic-version }}" == "true" ] && [ -n "${{ inputs.semantic-version }}" ]; then
            echo "VERSION=${{ inputs.semantic-version }}" >> $GITHUB_ENV
            echo "Using semantic version: ${{ inputs.semantic-version }}"
          elif [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
          fi
          echo "SHORT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
          # Set image name for frontend
          RAG_EVAL_UI_IMAGE="ghcr.io/${{ github.repository }}/rag-eval-ui"
          echo "RAG_EVAL_UI_IMAGE=${RAG_EVAL_UI_IMAGE}" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend container
        uses: docker/build-push-action@v6
        with:
          context: frontend/
          file: frontend/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.RAG_EVAL_UI_IMAGE }}:${{ env.SHORT_SHA }}
            ${{ inputs.use-semantic-version == 'true' && 
                format('{0}:{1}', env.RAG_EVAL_UI_IMAGE, env.VERSION) || '' }}
            ${{ github.ref_type == 'tag' &&
                format('{0}:{1}', env.RAG_EVAL_UI_IMAGE,
                       github.ref_name) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
