---
name: Frontend Build & Push

# Migrated from GitLab CI - supports manual dispatch
"on":
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag the Docker image with'
        required: false
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version to tag the Docker image with'
        required: false
        type: string

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  # Build and push frontend container - migrated from build-container-ui
  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Set initial version (pre-build)
        id: pre-version
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
          # Set image name for frontend
          RAG_EVAL_UI_IMAGE="ghcr.io/${{ github.repository }}/rag-eval-ui"
          echo "RAG_EVAL_UI_IMAGE=${RAG_EVAL_UI_IMAGE}" >> $GITHUB_ENV
          
          # Set initial version for build
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend container
        uses: docker/build-push-action@v6
        with:
          context: frontend/
          file: frontend/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.RAG_EVAL_UI_IMAGE }}:${{ env.SHORT_SHA }}
            ${{ github.ref_type == 'tag' &&
                format('{0}:{1}', env.RAG_EVAL_UI_IMAGE,
                       github.ref_name) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Tag and push semantic version if version was provided
      - name: Tag and push semantic version
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && inputs.version != ''
        run: |
          # Use the version provided by the bulk release workflow
          NEW_VERSION="${{ inputs.version }}"
          echo "Using version from bulk release: $NEW_VERSION"
          # Create frontend-prefixed version tag
          FRONTEND_VERSION="frontend-v$NEW_VERSION"
          echo "Using release tag: $FRONTEND_VERSION"
          
          # Tag the existing image with the frontend-prefixed semantic version
          docker pull ${{ env.RAG_EVAL_UI_IMAGE }}:${{ env.SHORT_SHA }}
          docker tag ${{ env.RAG_EVAL_UI_IMAGE }}:${{ env.SHORT_SHA }} ${{ env.RAG_EVAL_UI_IMAGE }}:$FRONTEND_VERSION
          docker push ${{ env.RAG_EVAL_UI_IMAGE }}:$FRONTEND_VERSION
          echo "Tagged and pushed image with frontend version: $FRONTEND_VERSION"
