---
name: Frontend Pipeline

"on":
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

permissions:
  contents: read
  security-events: write
  actions: read
  packages: write

jobs:
  # Parallel execution of lint, security-scan, and test workflows
  lint:
    name: Run Lint
    uses: ./.github/workflows/frontend/lint.yaml

  security-scan:
    name: Run Security Scan
    uses: ./.github/workflows/security-scan.yaml

  test:
    name: Run Test
    uses: ./.github/workflows/frontend/test.yaml

  # Sequential build stage - runs only after parallel jobs succeed
  build-and-push:
    name: Build and Push
    needs: [lint, security-scan, test]
    uses: ./.github/workflows/frontend/build-and-push.yaml
