---
name: Frontend Pipeline

"on":
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

permissions:
  contents: read
  security-events: write
  actions: read
  packages: write

jobs:
  # Parallel execution of lint, security-scan, and test workflows
  lint:
    name: Run Lint
    uses: ./.github/workflows/frontend-lint.yaml

  security-scan:
    name: Run Security Scan
    uses: ./.github/workflows/security-scan.yaml

  test:
    name: Run Test
    uses: ./.github/workflows/frontend-test.yaml

  # Semantic release - only on main branch pushes
  semantic-release:
    name: Semantic Release
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [lint, security-scan, test]
    uses: ./.github/workflows/frontend-semantic-release.yaml

  # Sequential build stage - runs only after parallel jobs succeed
  build-and-push:
    name: Build and Push
    needs: [lint, security-scan, test, semantic-release]
    if: always() && !cancelled() && !failure() && (needs.lint.result == 'success' && needs.security-scan.result == 'success' && needs.test.result == 'success')
    uses: ./.github/workflows/frontend-build-and-push.yaml
    with:
      semantic-version: ${{ needs.semantic-release.outputs.new-release-version || '' }}
      use-semantic-version: ${{ needs.semantic-release.outputs.new-release-published == 'true' }}
