---
name: Frontend Semantic Release

on:
  workflow_call:
    outputs:
      new-release-published:
        description: "Whether a new release was published"
        value: ${{ jobs.semantic-release.outputs.new-release-published }}
      new-release-version:
        description: "The new release version"
        value: ${{ jobs.semantic-release.outputs.new-release-version }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      new-release-published: ${{ steps.semantic.outputs.new-release-published }}
      new-release-version: ${{ steps.semantic.outputs.new-release-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd frontend
          npm run semantic-release