name: GitLab Migration Build Pipeline

# Migrated from GitLab CI - using dispatch trigger only as requested
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to use for build (defaults to commit SHA)'
        required: false
        type: string
        default: ''


permissions:
  contents: read
  packages: write

jobs:
  # Build frontend container - migrated from build-container-ui
  build-container-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set version
        id: version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          elif [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
          fi
          echo "SHORT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
      
      - uses: docker/setup-buildx-action@v3
      
      - name: Build frontend container
        uses: docker/build-push-action@v6
        with:
          context: frontend/
          file: frontend/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
            CI=true
          tags: rag-eval-ui:${{ env.SHORT_SHA }}
          outputs: type=docker,dest=/tmp/frontend.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend.tar
          path: /tmp/frontend.tar
          retention-days: 2

  # Build backend container - migrated from build-container-backend  
  build-container-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set version
        id: version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          elif [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
          fi
          echo "SHORT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
      
      - uses: docker/setup-buildx-action@v3
      
      - name: Build backend container
        uses: docker/build-push-action@v6
        with:
          context: backend/
          file: backend/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
            CI=true
          tags: llm-eval-backend:${{ env.SHORT_SHA }}
          outputs: type=docker,dest=/tmp/backend.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend.tar
          path: /tmp/backend.tar
          retention-days: 2

